apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: frr-k8s
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: frr-k8s-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: frr-k8s
    app.kubernetes.io/part-of: frr-k8s
    app.kubernetes.io/managed-by: kustomize
  name: frr-k8s-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: frr-k8s
