---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: daemon-role
rules:
- apiGroups:
  - frrk8s.metallb.io
  resources:
  - frrconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frrk8s.metallb.io
  resources:
  - frrconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - frrk8s.metallb.io
  resources:
  - frrconfigurations/status
  verbs:
  - get
  - patch
  - update
